{
 "title": "Ingeteam ISS 1 Play TL M",
 "description": "Dashboard para la monitorización del Ingecon Sun Storage 1 Play TL M",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Estado del Inversor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estado del Inversor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_inverter_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Horas de funcionamiento",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    { "expr": "modbus_op_time ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alarmas Inversor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_alarms", "legendFormat": "__auto" },
    { "expr": "modbus_code_1", "legendFormat": "__auto" },
    { "expr": "modbus_code_2", "legendFormat": "__auto" },
    { "expr": "modbus_code_3", "legendFormat": "__auto" },
    { "expr": "modbus_stop_event", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tiempo de espera para conectar a Red",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_waiting_time_to_connect_to_grid",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Fotovoltaica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Fotovoltaica Tensión",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_pv1_voltage", "legendFormat": "FV 1: Tensión" },
    { "expr": "modbus_pv2_voltage", "legendFormat": "FV 2: Tensión" }
   ]
  },
  {
   "title": "Fotovoltaica Tensión",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "modbus_pv1_voltage", "legendFormat": "FV 1: Tensión" },
    { "expr": "modbus_pv2_voltage", "legendFormat": "FV 2: Tensión" }
   ]
  },
  {
   "title": "Fotovoltaica Corriente",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "modbus_pv1_amps / 100", "legendFormat": "FV 1: Corriente" },
    { "expr": "modbus_pv2_amps / 100", "legendFormat": "FV 2: Corriente" }
   ]
  },
  {
   "title": "Fotovoltaica Corriente",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_pv1_amps / 100", "legendFormat": "FV 1: Corriente" },
    { "expr": "modbus_pv2_amps / 100", "legendFormat": "FV 2: Corriente" }
   ]
  },
  {
   "title": "Fotovoltaica Potencia",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_pv1_power", "legendFormat": "FV 1: Potencia" },
    { "expr": "modbus_pv2_power", "legendFormat": "FV 2: Potencia" }
   ]
  },
  {
   "title": "Fotovoltaica Potencia",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "modbus_pv1_power", "legendFormat": "FV 1: Potencia" },
    { "expr": "modbus_pv2_power", "legendFormat": "FV 2: Potencia" },
    {
     "expr": "modbus_pv1_power + modbus_pv2_power",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Fotovoltaica Potencia Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (modelo,fabricante,origen) (modbus_pv1_power) + sum by (modelo,fabricante,origen) (modbus_pv2_power)",
     "legendFormat": "FV: Potencia Total"
    }
   ]
  },
  { "title": "Bateria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Potencia Baterías",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_power", "legendFormat": "Battery Power " }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_max_discharging_amps / 100",
     "legendFormat": "Máxima Corriente de Descarga"
    },
    {
     "expr": "modbus_battery_max_charging_amps / 100",
     "legendFormat": "Máxima Corriente de Carga"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 11, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(modbus_battery_charge_limitation_reason, \"__name__\", \"Limitación Carga Bateria\", \"__name__\", \".*\")",
     "legendFormat": "Charge"
    },
    {
     "expr": "label_replace(modbus_battery_discharge_limitation_reason, \"__name__\", \"Limitación Descarga Bateria\", \"__name__\", \".*\")",
     "legendFormat": "Discharge"
    }
   ]
  },
  {
   "title": "Salud Baterías",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_soh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estado Baterías",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_status", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_bms_flags", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_warnings", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_errors", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_faults", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_protections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estado de Carga",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "modbus_battery_soc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alarmas BMS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_bms_alarms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tensión de Descarga",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_discharging_voltage / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tensión de Carga",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_charging_voltage / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corriente",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_amps / 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tensión",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_voltage / 10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_temperature / 10",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}