{
 "title": "Ingeteam ISS 1 Play TL M Baterias",
 "description": "Dashboard para la monitorización del Ingecon Sun Storage 1 Play TL M",
 "tags": [
  "Ingeteam",
  "Baterías"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; background-color: #1f78c1; color: white; padding: 20px; border-radius: 10px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <h1 style=\"margin: 0; font-size: 2.5em;\">🌟 Estado General de las Baterías 🌟</h1>\n  <p style=\"margin: 0; font-size: 1.2em; font-style: italic;\">Monitorización en Tiempo Real</p>\n</div>\n"
   }
  },
  {
   "title": "Potencia Baterías",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_power", "legendFormat": "Battery Power " }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_max_discharging_amps / 100",
     "legendFormat": "Máxima Corriente de Descarga"
    },
    {
     "expr": "modbus_battery_max_charging_amps / 100",
     "legendFormat": "Máxima Corriente de Carga"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 11, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(modbus_battery_charge_limitation_reason, \"__name__\", \"Limitación Carga Bateria\", \"__name__\", \".*\")",
     "legendFormat": "Charge"
    },
    {
     "expr": "label_replace(modbus_battery_discharge_limitation_reason, \"__name__\", \"Limitación Descarga Bateria\", \"__name__\", \".*\")",
     "legendFormat": "Discharge"
    }
   ]
  },
  {
   "title": "Salud Baterías",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_soh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estado Baterías",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_status", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_bms_flags", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_warnings", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_errors", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_faults", "legendFormat": "__auto" },
    { "expr": "modbus_battery_bms_protections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estado de Carga",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "modbus_battery_soc", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alarmas BMS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_bms_alarms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tensión de Descarga",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_discharging_voltage / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tensión de Carga",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_charging_voltage / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corriente",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_amps / 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tensión",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_battery_voltage / 10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_battery_temperature / 10",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}