{
 "title": "Ingeteam ISS 1 Play TL M Inversor",
 "description": "Dashboard para la monitorización del Ingecon Sun Storage 1 Play TL M",
 "tags": [
  "Ingeteam",
  "Inversor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; background-color: #1f78c1; color: white; padding: 20px; border-radius: 10px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <h1 style=\"margin: 0; font-size: 2.5em;\">🌟 Estado General del Inversor 🌟</h1>\n  <p style=\"margin: 0; font-size: 1.2em; font-style: italic;\">Monitorización en Tiempo Real</p>\n</div>\n"
   }
  },
  {
   "title": "Estado del Inversor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_inverter_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Horas de funcionamiento",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    { "expr": "modbus_op_time ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alarmas Inversor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_alarms", "legendFormat": "__auto" },
    { "expr": "modbus_code_1", "legendFormat": "__auto" },
    { "expr": "modbus_code_2", "legendFormat": "__auto" },
    { "expr": "modbus_code_3", "legendFormat": "__auto" },
    { "expr": "modbus_stop_event", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tiempo de espera para conectar a Red",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modbus_waiting_time_to_connect_to_grid",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}