{
 "title": "Ingeteam ISS 1 Play TL M Fotovoltaica",
 "description": "Dashboard para la monitorización del Ingecon Sun Storage 1 Play TL M",
 "tags": [
  "Ingeteam",
  "Fotovoltaica"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; background-color: #1f78c1; color: white; padding: 20px; border-radius: 10px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\">\n  <h1 style=\"margin: 0; font-size: 2.5em;\">🌟 Estado General de la Fotovoltáica 🌟</h1>\n  <p style=\"margin: 0; font-size: 1.2em; font-style: italic;\">Monitorización en Tiempo Real</p>\n</div>\n"
   }
  },
  {
   "title": "Fotovoltaica Tensión",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_pv1_voltage", "legendFormat": "FV 1: Tensión" },
    { "expr": "modbus_pv2_voltage", "legendFormat": "FV 2: Tensión" }
   ]
  },
  {
   "title": "Fotovoltaica Tensión",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "modbus_pv1_voltage", "legendFormat": "FV 1: Tensión" },
    { "expr": "modbus_pv2_voltage", "legendFormat": "FV 2: Tensión" }
   ]
  },
  {
   "title": "Fotovoltaica Corriente",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "modbus_pv1_amps / 100", "legendFormat": "FV 1: Corriente" },
    { "expr": "modbus_pv2_amps / 100", "legendFormat": "FV 2: Corriente" }
   ]
  },
  {
   "title": "Fotovoltaica Corriente",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_pv1_amps / 100", "legendFormat": "FV 1: Corriente" },
    { "expr": "modbus_pv2_amps / 100", "legendFormat": "FV 2: Corriente" }
   ]
  },
  {
   "title": "Fotovoltaica Potencia",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modbus_pv1_power", "legendFormat": "FV 1: Potencia" },
    { "expr": "modbus_pv2_power", "legendFormat": "FV 2: Potencia" }
   ]
  },
  {
   "title": "Fotovoltaica Potencia",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "modbus_pv1_power", "legendFormat": "FV 1: Potencia" },
    { "expr": "modbus_pv2_power", "legendFormat": "FV 2: Potencia" },
    {
     "expr": "modbus_pv1_power + modbus_pv2_power",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Fotovoltaica Potencia Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (modelo,fabricante,origen) (modbus_pv1_power) + sum by (modelo,fabricante,origen) (modbus_pv2_power)",
     "legendFormat": "FV: Potencia Total"
    }
   ]
  }
 ]
}